# practice Pandas from RealPython

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('data/legislators-historical.csv')
df

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,district,senate_class,party,url,address,phone,contact_form,rss_url,twitter,facebook,youtube,youtube_id,bioguide_id,thomas_id,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Bassett,Richard,NaN,NaN,NaN,NaN,1745-04-02,M,sen,DE,NaN,2.0,Anti-Administration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B000226,NaN,NaN,NaN,NaN,NaN,401222,NaN,NaN,NaN,507.0,Richard Bassett (Delaware politician)
1,Bland,Theodorick,NaN,NaN,NaN,NaN,1742-03-21,M,rep,VA,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B000546,NaN,NaN,NaN,NaN,NaN,401521,NaN,NaN,NaN,786.0,Theodorick Bland (congressman)
2,Burke,Aedanus,NaN,NaN,NaN,NaN,1743-06-16,M,rep,SC,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B001086,NaN,NaN,NaN,NaN,NaN,402032,NaN,NaN,NaN,1260.0,Aedanus Burke
3,Carroll,Daniel,NaN,NaN,NaN,NaN,1730-07-22,M,rep,MD,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C000187,NaN,NaN,NaN,NaN,NaN,402334,NaN,NaN,NaN,1538.0,Daniel Carroll
4,Clymer,George,NaN,NaN,NaN,NaN,1739-03-16,M,rep,PA,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C000538,NaN,NaN,NaN,NaN,NaN,402671,NaN,NaN,NaN,1859.0,George Clymer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12051,Young,Don,E.,NaN,NaN,Don Young,1933-06-09,M,rep,AK,0.0,NaN,Republican,https://donyoung.house.gov,2314 Rayburn House Office Building Washington ...,202-225-5765,NaN,http://donyoung.house.gov/news/rss.aspx,NaN,NaN,NaN,NaN,Y000033,1256.0,N00007999,NaN,H6AK00045,1897.0,400440,26717.0,Don Young,NaN,14066.0,Don Young
12052,Fortenberry,Jeff,Lane,NaN,NaN,Jeff Fortenberry,1960-12-27,M,rep,NE,1.0,NaN,Republican,https://fortenberry.house.gov,1514 Longworth House Office Building Washingto...,202-225-4806,NaN,http://fortenberry.house.gov/index.php?format=...,NaN,NaN,NaN,NaN,F000449,1793.0,N00026631,NaN,H4NE01064,1013049.0,400640,41929.0,Jeff Fortenberry,NaN,20518.0,Jeff Fortenberry
12053,Vela,Filemon,NaN,NaN,NaN,Filemon Vela,1963-02-13,M,rep,TX,34.0,NaN,Democrat,https://vela.house.gov,307 Cannon House Office Building Washington DC...,202-225-9901,NaN,http://vela.house.gov/rss.xml,NaN,NaN,NaN,NaN,V000132,2167.0,N00034349,NaN,H2TX27190,95434.0,412580,137719.0,Filemon Vela,NaN,21366.0,Filemon Vela Jr.
12054,Reed,Tom,W.,NaN,NaN,Tom Reed,1971-11-18,M,rep,NY,23.0,NaN,Republican,https://reed.house.gov,1203 Longworth House Office Building Washingto...,202-225-3161,NaN,http://reed.house.gov/rss.xml,NaN,NaN,NaN,NaN,R000585,1982.0,N00030949,NaN,H0NY29054,623468.0,412393,127046.0,Tom Reed (New York),NaN,21101.0,Tom Reed (politician)
12055,Delgado,Antonio,NaN,NaN,NaN,Antonio Delgado,1977-01-19,M,rep,NY,19.0,NaN,Democrat,https://delgado.house.gov,1007 Longworth House Office Building Washingto...,202-225-5614,NaN,NaN,NaN,NaN,NaN,NaN,D000630,NaN,N00040741,NaN,H8NY19181,NaN,412805,180313.0,Antonio Delgado (New York),NaN,21916.0,Antonio Delgado (politician)

In [5]:
df.groupby('state').count()

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,district,senate_class,party,url,address,phone,contact_form,rss_url,twitter,facebook,youtube,youtube_id,bioguide_id,thomas_id,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
state,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
AK,17,17,13,0,2,2,17,17,17,11,6,15,3,2,2,1,2,0,0,0,0,17,5,3,3,3,2,17,3,2,0,10,17
AL,209,209,154,12,5,7,200,209,209,169,40,209,12,7,7,5,4,0,0,0,0,209,31,12,4,12,10,209,12,7,0,208,209
AR,117,117,92,8,4,3,114,117,117,84,33,115,6,3,3,3,2,0,0,0,0,117,22,6,5,6,6,117,6,3,0,115,117
AS,2,2,2,0,0,1,2,2,2,2,0,2,1,1,1,1,0,0,0,0,0,2,2,1,0,1,1,2,1,0,0,0,2
AZ,49,49,35,4,2,9,49,49,49,37,12,49,15,10,9,7,5,0,0,0,0,49,28,15,5,13,10,49,14,7,0,41,49
CA,368,368,291,12,14,40,365,368,368,325,43,368,57,41,41,27,18,0,0,0,0,368,149,58,5,50,38,368,52,16,0,367,367
CO,92,92,76,1,6,5,92,92,92,57,35,92,15,5,5,2,4,0,0,0,0,92,31,16,8,11,8,92,13,5,0,90,92
CT,240,240,146,7,2,2,238,240,240,189,51,227,6,2,2,1,1,0,0,0,0,240,23,6,2,4,2,240,4,2,0,240,240
DC,2,2,2,0,0,0,2,2,2,2,0,2,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,2,0,0,0,0,2
DE,97,97,70,15,0,1,91,97,97,48,49,94,4,1,1,1,1,0,0,0,0,97,7,4,3,3,4,97,4,2,0,97,97
DK,9,9,8,0,0,0,9,9,9,9,0,8,0,0,0,0,0,0,0,0,0,9,0,0,0,0,0,9,0,0,0,0,9
FL,161,161,103,14,14,31,158,161,161,129,32,157,53,31,31,15,16,0,0,0,0,161,88,54,5,45,31,161,45,25,0,154,161
GA,317,317,217,15,10,16,297,317,317,256,61,311,24,16,16,10,12,0,0,0,0,317,53,26,9,20,16,317,20,15,0,311,317
GU,4,4,4,0,0,1,4,4,4,4,0,4,1,1,1,0,1,0,0,0,0,4,4,1,0,1,1,4,1,0,0,0,4
HI,24,24,20,0,0,5,24,24,24,19,5,23,7,5,5,2,2,0,0,0,0,24,12,7,3,7,5,24,6,2,0,13,24
IA,205,205,168,0,4,9,204,205,205,173,32,205,11,9,9,4,5,0,0,0,0,205,27,11,1,9,8,205,9,7,0,204,205
ID,59,59,45,1,1,1,59,59,59,35,24,59,5,1,1,0,1,0,0,0,0,59,14,5,4,4,2,59,5,1,0,50,59
IL,488,488,390,7,5,16,480,488,488,442,46,485,30,16,16,9,8,0,0,0,0,488,82,31,7,25,19,488,25,12,0,485,488
IN,343,343,256,5,4,10,337,343,343,299,44,340,18,10,10,6,7,0,0,0,0,343,50,19,4,16,11,343,20,8,0,341,343
KS,143,143,109,3,3,6,143,143,143,111,32,143,11,6,6,2,5,0,0,0,0,143,27,11,5,10,6,143,11,6,0,141,143
KY,373,373,261,10,6,2,342,373,373,315,58,368,8,3,3,3,1,0,0,0,0,373,24,8,2,5,4,373,6,2,0,371,373
LA,199,199,149,14,7,9,184,199,199,153,46,196,19,9,9,6,6,0,0,0,0,199,39,19,4,16,10,199,16,9,0,197,199
MA,427,427,232,18,5,9,420,427,427,381,46,411,13,9,9,6,3,0,0,0,0,427,35,14,5,11,9,427,12,5,0,426,427
MD,305,305,197,15,1,5,274,305,305,252,53,286,9,5,5,3,4,0,0,0,0,305,28,10,2,8,6,305,8,3,0,305,305
ME,175,175,99,6,1,3,173,175,175,140,35,170,4,3,3,2,1,0,0,0,0,175,15,4,3,4,2,175,4,1,0,175,175
MI,296,296,238,9,5,17,294,296,296,260,36,292,24,18,18,9,10,0,0,0,0,296,66,26,3,24,18,296,25,12,0,291,296
MN,162,162,126,1,4,11,162,162,162,128,34,161,18,11,11,3,8,0,0,0,0,162,42,18,8,14,10,162,14,9,0,160,162
MO,334,334,278,10,10,5,326,334,334,291,43,331,11,5,5,4,1,0,0,0,0,334,36,11,6,8,8,334,8,2,0,332,334
MS,155,155,117,2,5,3,139,155,155,113,42,151,7,3,3,2,3,0,0,0,0,155,19,7,2,7,6,155,7,3,0,152,155
MT,53,53,37,0,3,5,53,53,53,33,20,53,6,5,5,3,1,0,0,0,0,53,13,7,3,5,3,53,5,2,0,47,53
NC,356,356,236,14,7,14,315,356,356,306,50,345,21,14,14,9,9,0,0,0,0,356,53,21,6,17,14,356,18,10,0,355,356
ND,44,44,36,0,0,3,44,44,44,22,22,44,5,3,3,2,1,0,0,0,0,44,9,5,5,5,4,44,5,1,0,43,44
NE,128,128,110,0,4,5,127,128,128,92,36,127,8,5,5,3,3,0,0,0,0,128,23,8,5,6,4,128,7,3,0,121,128
NH,181,181,88,9,3,4,178,181,181,121,60,176,8,4,4,1,2,0,0,0,0,181,20,8,6,7,5,181,7,2,0,181,181
NJ,359,359,239,18,4,11,343,359,359,299,60,349,16,12,12,8,7,0,0,0,0,359,53,15,5,14,13,359,16,4,0,358,359
NM,57,57,42,1,1,6,57,57,57,41,16,55,9,6,6,2,3,0,0,0,0,57,15,9,3,9,5,57,9,6,0,42,57
NV,56,56,46,2,3,6,56,56,56,32,24,55,9,7,6,4,2,0,0,0,0,56,17,9,4,8,5,56,8,4,0,53,56
NY,1469,1469,925,47,10,29,1382,1469,1469,1414,55,1434,49,30,29,13,16,0,0,0,0,1469,127,49,3,43,28,1469,43,16,0,1465,1469
OH,676,676,486,17,6,10,641,676,676,624,52,669,25,10,10,6,5,0,0,0,0,676,75,26,4,21,16,676,21,7,0,672,676
OK,93,93,73,3,2,6,93,93,93,77,16,93,10,6,6,3,1,0,0,0,0,93,27,11,3,7,5,93,8,3,0,90,93
OL,2,2,1,0,0,0,1,2,2,2,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,2,0,0,0,0,2
OR,90,90,68,2,1,1,89,90,90,56,34,90,4,2,1,0,1,0,0,0,0,90,19,4,3,4,2,90,4,1,0,89,90
PA,1053,1053,650,35,7,18,977,1053,1053,1003,50,1035,33,18,18,9,13,0,0,0,0,1053,96,34,4,27,23,1053,30,12,0,1050,1053
PI,13,13,6,0,0,0,13,13,13,13,0,0,0,0,0,0,0,0,0,0,0,13,0,0,0,0,0,13,0,0,0,0,13
PR,19,19,9,0,0,1,19,19,19,19,0,19,3,1,1,1,1,0,0,0,0,19,8,3,0,2,1,19,2,0,0,0,19
RI,107,107,70,4,0,0,104,107,107,62,45,105,2,0,0,0,0,0,0,0,0,107,11,2,3,1,1,107,1,1,0,107,107
SC,251,251,168,13,4,5,222,251,251,198,53,244,10,5,5,1,3,0,0,0,0,251,25,10,3,9,8,251,9,5,0,250,251
SD,51,51,43,0,3,2,51,51,51,26,25,51,5,2,2,1,2,0,0,0,0,51,11,5,3,3,3,51,3,2,0,49,51
TN,301,301,217,9,6,6,279,301,301,244,57,299,14,6,6,3,5,0,0,0,0,301,36,15,7,11,10,301,12,4,0,300,301
TX,264,264,204,14,20,28,263,264,264,234,30,264,40,28,28,9,18,0,0,0,0,264,95,41,4,32,28,264,32,17,0,264,264
UT,55,55,40,1,3,7,55,55,55,40,15,55,8,6,6,2,3,0,0,0,0,55,21,8,3,8,6,55,8,5,0,50,55
VA,433,433,267,27,7,13,377,433,433,384,49,419,23,13,13,7,7,0,0,0,0,433,44,23,4,21,15,433,22,10,0,433,433
VI,4,4,3,0,0,1,4,4,4,4,0,4,1,1,1,1,1,0,0,0,0,4,4,1,0,1,1,4,1,1,0,0,4
VT,115,115,53,3,3,0,112,115,115,79,36,111,1,0,0,0,0,0,0,0,0,115,5,1,1,0,0,115,0,0,0,115,115
WA,96,96,76,2,7,5,96,96,96,76,20,96,9,6,6,4,4,0,0,0,0,96,33,9,2,7,7,96,7,3,0,84,96
WI,198,198,162,5,4,6,198,198,198,172,26,198,11,6,6,3,5,0,0,0,0,198,32,12,3,9,9,198,10,7,0,196,198
WV,120,120,103,10,1,3,118,120,120,89,31,120,5,3,3,2,2,0,0,0,0,120,16,6,3,5,6,120,7,2,0,120,120
WY,40,40,37,0,1,1,40,40,40,20,20,40,3,1,1,1,1,0,0,0,0,40,9,3,4,3,2,40,2,1,0,34,40

In [6]:
by_state =  df.groupby('state')['last_name', 'middle_name'].count()
by_state

/tmp/ipykernel_249304/2273736461.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  by_state =  df.groupby('state')['last_name', 'middle_name'].count()

       last_name  middle_name
state
AK            17           13
AL           209          154
AR           117           92
AS             2            2
AZ            49           35
CA           368          291
CO            92           76
CT           240          146
DC             2            2
DE            97           70
DK             9            8
FL           161          103
GA           317          217
GU             4            4
HI            24           20
IA           205          168
ID            59           45
IL           488          390
IN           343          256
KS           143          109
KY           373          261
LA           199          149
MA           427          232
MD           305          197
ME           175           99
MI           296          238
MN           162          126
MO           334          278
MS           155          117
MT            53           37
NC           356          236
ND            44           36
NE           128          110
NH           181           88
NJ           359          239
NM            57           42
NV            56           46
NY          1469          925
OH           676          486
OK            93           73
OL             2            1
OR            90           68
PA          1053          650
PI            13            6
PR            19            9
RI           107           70
SC           251          168
SD            51           43
TN           301          217
TX           264          204
UT            55           40
VA           433          267
VI             4            3
VT           115           53
WA            96           76
WI           198          162
WV           120          103
WY            40           37

In [7]:
df.groupby(['state', 'gender'])['last_name', 'middle_name'].count().head(50)

/tmp/ipykernel_249304/2715983420.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['state', 'gender'])['last_name', 'middle_name'].count().head(50)

              last_name  middle_name
state gender
AK    M              17           13
AL    F               4            3
      M             205          151
AR    F               5            5
      M             112           87
AS    M               2            2
AZ    F               4            1
      M              45           34
CA    F              26           13
      M             342          278
CO    F               3            2
      M              89           74
CT    F               6            6
      M             234          140
DC    M               2            2
DE    M              97           70
DK    M               9            8
FL    F              14            4
      M             147           99
GA    F               8            4
      M             309          213
GU    F               1            1
      M               3            3
HI    F               5            4
      M              19           16
IA    F               1            0
      M             204          168
ID    F               2            1
      M              57           44
IL    F              13            9
      M             475          381
IN    F               6            6
      M             337          250
KS    F               7            4
      M             136          105
KY    F               2            2
      M             371          259
LA    F               5            5
      M             194          144
MA    F               4            4
      M             423          228
MD    F               8            7
      M             297          190
ME    F               2            2
      M             173           97
MI    F               7            4
      M             289          234
MN    F               3            3
      M             159          123
MO    F               7            3

In [8]:
df.groupby(['state', 'gender'], as_index=False)['last_name', 'middle_name'].count().head(6)

/tmp/ipykernel_249304/3872729061.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['state', 'gender'], as_index=False)['last_name', 'middle_name'].count().head(6)

  state gender  last_name  middle_name
0    AK      M         17           13
1    AL      F          4            3
2    AL      M        205          151
3    AR      F          5            5
4    AR      M        112           87
5    AS      M          2            2